# Generated by Django 5.0.6 on 2026-05-13 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("morning", "朝"), ("afternoon", "帰宅後"), ("night", "夜")],
                        max_length=20,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("is_custom", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prep_items",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("child_icon", models.CharField(blank=True, max_length=255, null=True)),
                ("child_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prep_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="children",
                        to="kids_board.prepitem",
                        verbose_name="お支度項目",
                    ),
                ),
            ],
            options={
                "db_table": "children",
            },
        ),
        migrations.CreateModel(
            name="PrepItemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="kids_board.child",
                    ),
                ),
                (
                    "prep_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="kids_board.prepitem",
                    ),
                ),
            ],
            options={
                "db_table": "prep_items_logs",
            },
        ),
        migrations.CreateModel(
            name="PrepRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("weekday", "平日"),
                            ("holiday", "祝日"),
                            ("day_of_week", "曜日指定"),
                            ("specific", "特定日"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day_of_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("specific_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prep_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="kids_board.prepitem",
                    ),
                ),
            ],
            options={
                "db_table": "prep_rules",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schedule_date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (1, "赤"),
                            (2, "黄色"),
                            (3, "緑"),
                            (4, "エメラルドグリーン"),
                            (5, "水色"),
                            (6, "青"),
                            (7, "紫"),
                            (8, "ピンク"),
                            (9, "オレンジ"),
                            (10, "白"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="kids_board.child",
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
            },
        ),
        migrations.AddConstraint(
            model_name="prepitem",
            constraint=models.UniqueConstraint(
                fields=("parent", "category_type", "item_name"),
                name="unique_parent_category_type_item_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="child",
            constraint=models.UniqueConstraint(
                fields=("parent", "child_name"), name="unique_parent_child_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="prepitemlog",
            constraint=models.UniqueConstraint(
                fields=("child", "prep_item", "target_date"), name="unique_child_prep_item_date"
            ),
        ),
    ]
