# Generated by Django 5.0.6 on 2026-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepitem",
            name="prep_icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
