# Generated by Django 5.0.6 on 2026-04-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule_type", models.CharField(max_length=20)),
                ("weekday", models.BooleanField(default=False)),
                ("day_of_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("specific_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prep_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="kids_board.prepitem",
                    ),
                ),
            ],
            options={
                "db_table": "prep_rules",
            },
        ),
    ]
