# Generated by Django 5.0.6 on 2026-04-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0002_preprule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_at", models.DateField()),
                ("end_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "specific_dates",
            },
        ),
    ]
