# Generated by Django 5.0.6 on 2026-04-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0003_specificdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPrepItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "prep_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_items",
                        to="kids_board.prepitem",
                    ),
                ),
            ],
            options={
                "db_table": "daily_prep_items",
            },
        ),
    ]
