# Generated by Django 5.0.6 on 2026-04-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0004_dailyprepitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("schedule_type", models.CharField(max_length=20)),
                ("color", models.IntegerField()),
                ("day_of_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("specific_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="kids_board.child",
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
            },
        ),
    ]
