# Generated by Django 5.0.6 on 2026-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0005_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildrenIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("icon_name", models.CharField(max_length=255)),
                ("icon_image", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "children_icons",
            },
        ),
    ]
