# Generated by Django 5.0.6 on 2026-05-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids_board", "0007_prepicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprule",
            name="rule_type",
            field=models.CharField(
                choices=[("weekday", "平日"), ("specific", "特定日")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="preprule",
            name="specific_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prep_rules",
                to="kids_board.specificdate",
            ),
        ),
    ]
