server {
    listen 80;
    # nginxが80番ポートで待ち受ける

    # staticファイル配信

    # /static/が来たら
    location /static/ {

        # alias→ このURLがきたら、このディレクトリを見る
        alias /app/staticfiles/;

    }

        
    # /に来たリクエストを
    location / {

        # Docker内のwebコンテナの8000番へ転送
        proxy_pass http://web:8000;

        # ブラウザが指定したHostを、そのままDjangoにも伝える
        proxy_set_header Host $host;
        # proxy_set_header：NginxがDjangoに転送するとき、HTTPヘッダーをこう設定して渡してね。と言う意味
        # Host：ブラウザが、どのドメインにアクセスしたいかを伝える情報
        # $host：Nginxが受け取ったリクエストのHostをそのまま使う変数

        # アクセス元IPをDjangoに教える
        proxy_set_header X-Real-IP $remote_addr;
        # $remote_addr　→ Nginxから見たアクセスしてるPCのIP
        # このIPは認証やログ用途で使用される

        # クライアントIPアドレスの履歴をX-Forwarded-Forヘッダーへ追加する
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # $proxy_add_x_forwarded_for　↓
        # 既存のX-Forwarded-Forに現在のアクセス元IP($remote_addr)を追加した値

        # Djangoにhttp/httpsどちらの通信かを伝える
        proxy_set_header X-Forwarded-Proto $scheme;
        # $scheme:
        # nginxが受け取ったリクエストのプロトコル(http/https)を保持している変数

        

        
    }


}